Add /lookup specification
sparkfabrik/nominatim-openapi pull request #7
Opened 2023-09-28 13:51 UTC by tegola

Closes #4

2023-09-29 14:03 UTC, jenkin commented
After #8 merging, please rebase main branch into this one and re-run `make checksum` to fix checksum file.

2023-09-29 14:52 UTC, tegola commented
Rebased, no need to run `make checksum` (I did anyway to check there weren't changes) since I had already used `shasum` to generate the checksum.

2023-09-29 14:54 UTC, tegola commented
Uh, my bad. There is actualy a change to push. The slow vscode refresh and a misunderstanding made me think there wasn't any. Commit incoming.

2023-10-02 13:08 UTC, jenkin commented on docs/nominatim.openapi.json
> +                "operationId": "123",
Should be `lookup`, not `123`...

2023-10-02 13:16 UTC, jenkin requested changes
Very nice, thank you! Just three more changes and this PR can be merged... 😃

2023-10-02 13:16 UTC, jenkin commented on docs/nominatim.openapi.json
> +                "operationId": "123",
```suggestion
                "operationId": "lookup",
```

2023-10-02 13:16 UTC, jenkin commented on docs/nominatim.openapi.json
> +                    {
You totally missed the only required parameter `osm_ids` (see the [official docs](https://nominatim.org/release-docs/develop/api/Lookup/#endpoint))... 😄 

```suggestion
                "parameters": [
                    {
                        "schema": {
                            "type": "string",
                            "pattern": "^([RWN][0-9]+,?)+$"
                        },
                        "in": "query",
                        "name": "osm_ids",
                        "required": true,
                        "description": "Comma-separated list of OSM ids each prefixed with its type, one of node(N), way(W) or relation(R). Up to 50 ids can be queried at the same time."
                    },
                    {
```

2023-10-02 13:16 UTC, jenkin commented on docs/nominatim.openapi.json
> +                        "description": "Limit search results to one or more countries. `<countrycode>` must be the [ISO 3166-1alpha2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code. Each plac
There is no mention to `countrycodes` in the [official docs](https://nominatim.org/release-docs/develop/api/Lookup/#endpoint)...

```suggestion
```

2023-10-02 13:21 UTC, jenkin commented
@tegola Please rebase the main branch another time, I fixed the git hooks issue.

2023-10-02 13:58 UTC, jenkin approved these changes

2023-10-02 13:59 UTC, merged